[2024-12-17T13:53:58.700+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: arsenal_mancity_player_to_postgres.process_mancity_player manual__2024-12-17T13:53:55.006645+00:00 [queued]>
[2024-12-17T13:53:58.707+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: arsenal_mancity_player_to_postgres.process_mancity_player manual__2024-12-17T13:53:55.006645+00:00 [queued]>
[2024-12-17T13:53:58.707+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-17T13:53:58.718+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_mancity_player> on 2024-12-17 13:53:55.006645+00:00
[2024-12-17T13:53:58.737+0000] {standard_task_runner.py:57} INFO - Started process 34166 to run task
[2024-12-17T13:53:58.739+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'arsenal_mancity_player_to_postgres', 'process_mancity_player', 'manual__2024-12-17T13:53:55.006645+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/arsenal_mancity_player_to_postgres.py', '--cfg-path', '/tmp/tmp5t8aa1fe']
[2024-12-17T13:53:58.744+0000] {standard_task_runner.py:85} INFO - Job 425: Subtask process_mancity_player
[2024-12-17T13:53:58.819+0000] {task_command.py:410} INFO - Running <TaskInstance: arsenal_mancity_player_to_postgres.process_mancity_player manual__2024-12-17T13:53:55.006645+00:00 [running]> on host 653f470dc9b4
[2024-12-17T13:53:58.925+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='arsenal_mancity_player_to_postgres' AIRFLOW_CTX_TASK_ID='process_mancity_player' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T13:53:55.006645+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T13:53:55.006645+00:00'
[2024-12-17T13:53:58.926+0000] {logging_mixin.py:149} INFO - Downloading 'mancity_player.json' from bucket 'mancity-data'...
[2024-12-17T13:53:59.323+0000] {logging_mixin.py:149} INFO - File 'mancity_player.json' successfully downloaded to '/tmp/mancity_player.json'.
[2024-12-17T13:53:59.333+0000] {logging_mixin.py:149} INFO - Loading data from 'mancity_player.json' into PostgreSQL...
[2024-12-17T13:53:59.346+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/arsenal_mancity_player_to_postgres.py", line 115, in download_and_load
    load_json_to_postgres(file_name)
  File "/opt/airflow/dags/arsenal_mancity_player_to_postgres.py", line 74, in load_json_to_postgres
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "***-db" (172.29.0.5), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-12-17T13:53:59.474+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=arsenal_mancity_player_to_postgres, task_id=process_mancity_player, execution_date=20241217T135355, start_date=20241217T135358, end_date=20241217T135359
[2024-12-17T13:53:59.543+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 425 for task process_mancity_player (connection to server at "***-db" (172.29.0.5), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 34166)
[2024-12-17T13:53:59.591+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-17T13:53:59.682+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
